name: End-to-end tests
on: push
jobs:
  cypress-run: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Adjust if needed
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-    
      - name: Install dependencies
        run: npm install
      - name: Run Cypress tests and generate reports
        run: npm run cypress:run:report 
      - name: Upload Cypress reports
        uses: actions/upload-artifact@v4
        with:
           name: cypress-reports
           path: cypress/reports/html
           retention-days: 30
