name: End-to-end tests
on: push
jobs:
  cypress-run: 
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        spec: ['test:Molded-Test', 'test:Boards-Test'] 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
         command: npm run ${{ matrix.spec }} 
         record: true
        env:
         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
           name: cypress-reports-$(echo ${{ matrix.spec }} | sed 's/:/-/g')
           path: cypress/reports/html
           retention-days: 30
