name: End-to-end tests
on: push
jobs:
  cypress-run: 
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        run: npm run test:Molded-Test && npm run test:Boards-Test         
        env:
         CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
           name: cypress-execution-report
           path: cypress/reports/html
           retention-days: 30
